# Generated by scripts/update-tap.sh in https://github.com/nftechie/snapcap.
# Edit packaging/homebrew/snapcap.rb there instead of this file.
cask "snapcap" do
  version "0.1.1"
  sha256 "b2ddc040cc40ab363b90a260a79614b0a4c5b736e71cec108a6d85980ee3b2e9"

  url "https://github.com/nftechie/snapcap/releases/download/v#{version}/Snapcap-#{version}.dmg"
  name "Snapcap"
  desc "Local-first screen recorder with an editable camera bubble"
  homepage "https://github.com/nftechie/snapcap"

  # Releases are Apple Silicon only for now.
  depends_on arch: :arm64
  depends_on macos: :sequoia

  app "Snapcap.app"

  # Needed only while releases aren't notarized: Homebrew quarantines the
  # download and Gatekeeper then refuses to open an ad-hoc signed app.
  # scripts/update-tap.sh uncomments this block when STRIP_QUARANTINE=1.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{appdir}/Snapcap.app"]
  end

  uninstall quit: "com.alexwormuth.Snapcap"

  # Recordings are the user's files and are never zapped.
  zap trash: [
    "~/Library/Preferences/com.alexwormuth.Snapcap.plist",
    "~/Library/Saved Application State/com.alexwormuth.Snapcap.savedState",
  ]
end
